---
- hosts: localhost
  connection: local
  vars_files:
    - vars/connection_vars.yml

  tasks:
  - name: Create Digitalocean droplet
    community.digitalocean.digital_ocean_droplet:
      state: present
      oauth_token: "{{ u_token }}"
      name: SolrEngine
      private_networking: true
      size: s-1vcpu-512mb-10gb
      image: ubuntu-23-10-x64
      region: fra1
      ssh_keys: "{{ u_ssh }}"
      unique_name: true
    register: do

  - import_tasks: tasks/inventory_auto.yml