---
- name: Download Solr.
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
    dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
    mode: "0644"

- name: Expand Solr.
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
    dest: "{{ download_dir }}"
    remote_src: true
    creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

- name: Run Solr installation script.
  ansible.builtin.command: >
    {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
    {{ download_dir }}/solr-{{ solr_version }}.tgz
    -i /opt
    -d /var/solr
    -u solr
    -s solr
    -p 8983
    creates={{ solr_dir }}/bin/solr

- name: Ensure solr is started end enabled on boot.
  ansible.builtin.service:
    name: solr
    state: started
    enabled: "yes"
