name: Lint Ansible playbooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        pip install ansible ansible-lint

    - name: Lint Ansible playbook
      run: |
        ansible-lint droplet.yml
        ansible-lint solr.yml
        ansible-lint tasks/inventory_auto.yml
        ansible-lint tasks/solr_engine.yml
